// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdD9ZgopWFRlRdXWQDZKOyn1cW2IddFSk',
    appId: '1:948128026655:web:db495c913ccc16dfd1c52a',
    messagingSenderId: '948128026655',
    projectId: 'flutter-jarvis',
    authDomain: 'flutter-jarvis.firebaseapp.com',
    storageBucket: 'flutter-jarvis.appspot.com',
    measurementId: 'G-T5R7CZE8LE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs3jfCcc3YD31kb_jX2fnR94Y9_a462EM',
    appId: '1:948128026655:android:4f4dc81e7f9ebdb9d1c52a',
    messagingSenderId: '948128026655',
    projectId: 'flutter-jarvis',
    storageBucket: 'flutter-jarvis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf57YSfYqiAFu3htn2ipzzb8KfKUY1u0A',
    appId: '1:948128026655:ios:893ed182807ea6b9d1c52a',
    messagingSenderId: '948128026655',
    projectId: 'flutter-jarvis',
    storageBucket: 'flutter-jarvis.appspot.com',
    iosClientId: '948128026655-en01kvqt5bei64fmgummi878q2jqmjc4.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarvis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf57YSfYqiAFu3htn2ipzzb8KfKUY1u0A',
    appId: '1:948128026655:ios:893ed182807ea6b9d1c52a',
    messagingSenderId: '948128026655',
    projectId: 'flutter-jarvis',
    storageBucket: 'flutter-jarvis.appspot.com',
    iosClientId: '948128026655-en01kvqt5bei64fmgummi878q2jqmjc4.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarvis',
  );
}
